const empleades = [
  {
    nombre: "Wade Morgan",
    pais: "México",
    edad: 20,
    area: "QA",
    puesto: "Backend Developer",
    seniority: "Semisenior",
    sueldo: 79767,
    haceGuardia: false,
    lenguajes: ["Java"],
  },
  {
    nombre: "Eunice Browning",
    pais: "Colombia",
    edad: 20,
    area: "QA",
    puesto: "Data analyst",
    seniority: "Junior",
    sueldo: 72457,
    haceGuardia: true,
    lenguajes: ["Ruby", "C#", "Java", "Python", "PHP"],
  },
  {
    nombre: "Floyd Reyes",
    pais: "Paraguay",
    edad: 29,
    area: "Soporte",
    puesto: "Backend Developer",
    seniority: "Semisenior",
    sueldo: 64868,
    haceGuardia: false,
    lenguajes: ["Python", "Ruby", "Java", "C#"],
  },
  {
    nombre: "Downs Mccray",
    pais: "Brasil",
    edad: 46,
    area: "Soporte",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 40037,
    haceGuardia: false,
    lenguajes: ["Ruby", "JavaScript", "Python", "Java"],
  },
  {
    nombre: "Lynda Herring",
    pais: "Colombia",
    edad: 32,
    area: "Soporte",
    puesto: "Frontend Developer",
    seniority: "Trainee",
    sueldo: 71813,
    haceGuardia: true,
    lenguajes: ["PHP", "JavaScript"],
  },
  {
    nombre: "Tia Snider",
    pais: "Bolivia",
    edad: 40,
    area: "Seguridad",
    puesto: "Backend Developer",
    seniority: "Senior",
    sueldo: 53372,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Madelyn Berger",
    pais: "Colombia",
    edad: 34,
    area: "Infraestructura",
    puesto: "Data analyst",
    seniority: "Trainee",
    sueldo: 73521,
    haceGuardia: true,
    lenguajes: ["Ruby", "PHP", "JavaScript", "Python", "Java", "C#"],
  },
  {
    nombre: "Tiffany Estrada",
    pais: "Brasil",
    edad: 33,
    area: "Desarrollo",
    puesto: "Frontend Developer",
    seniority: "Trainee",
    sueldo: 79101,
    haceGuardia: false,
    lenguajes: ["C#", "Ruby"],
  },
  {
    nombre: "Ellis Trevino",
    pais: "Bolivia",
    edad: 30,
    area: "Desarrollo",
    puesto: "Architect",
    seniority: "Senior",
    sueldo: 27676,
    haceGuardia: true,
    lenguajes: ["Python", "PHP", "JavaScript", "Ruby", "C#"],
  },
  {
    nombre: "Dolly Barnett",
    pais: "Uruguay",
    edad: 31,
    area: "Soporte",
    puesto: "Analyst",
    seniority: "Senior",
    sueldo: 35665,
    haceGuardia: false,
    lenguajes: ["Python", "C#", "PHP"],
  },
  {
    nombre: "Short Butler",
    pais: "Venezuela",
    edad: 38,
    area: "Seguridad",
    puesto: "DevOps",
    seniority: "Junior",
    sueldo: 99270,
    haceGuardia: true,
    lenguajes: [],
  },
  {
    nombre: "Beard Green",
    pais: "Bolivia",
    edad: 35,
    area: "Seguridad",
    puesto: "Frontend Developer",
    seniority: "Semisenior",
    sueldo: 37729,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "House Morse",
    pais: "Paraguay",
    edad: 35,
    area: "Soporte",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 45354,
    haceGuardia: false,
    lenguajes: ["JavaScript", "PHP", "Python"],
  },
  {
    nombre: "Butler Lynch",
    pais: "Colombia",
    edad: 20,
    area: "QA",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 22885,
    haceGuardia: false,
    lenguajes: ["JavaScript", "C#", "Python", "Java", "Ruby", "PHP"],
  },
  {
    nombre: "Jennifer Snyder",
    pais: "Colombia",
    edad: 42,
    area: "Infraestructura",
    puesto: "Backend Developer",
    seniority: "Junior",
    sueldo: 86688,
    haceGuardia: true,
    lenguajes: ["Python", "C#"],
  },
  {
    nombre: "Peterson Arnold",
    pais: "Uruguay",
    edad: 47,
    area: "QA",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 91786,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Cherry Valencia",
    pais: "Colombia",
    edad: 47,
    area: "Soporte",
    puesto: "Architect",
    seniority: "Semisenior",
    sueldo: 84314,
    haceGuardia: true,
    lenguajes: ["Java", "C#", "Python", "PHP"],
  },
  {
    nombre: "Sheila Ayala",
    pais: "Colombia",
    edad: 38,
    area: "Desarrollo",
    puesto: "Tester",
    seniority: "Junior",
    sueldo: 87495,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Ola Levy",
    pais: "Paraguay",
    edad: 42,
    area: "QA",
    puesto: "Architect",
    seniority: "Junior",
    sueldo: 57677,
    haceGuardia: true,
    lenguajes: ["PHP", "Java", "Python"],
  },
  {
    nombre: "Madden Bright",
    pais: "Venezuela",
    edad: 39,
    area: "Soporte",
    puesto: "Backend Developer",
    seniority: "Trainee",
    sueldo: 65301,
    haceGuardia: true,
    lenguajes: ["PHP"],
  },
  {
    nombre: "Tammie Merrill",
    pais: "México",
    edad: 38,
    area: "Infraestructura",
    puesto: "Analyst",
    seniority: "Junior",
    sueldo: 93098,
    haceGuardia: true,
    lenguajes: ["Ruby", "PHP", "Java", "C#", "JavaScript"],
  },
  {
    nombre: "Nita Buchanan",
    pais: "México",
    edad: 37,
    area: "Seguridad",
    puesto: "Tester",
    seniority: "Junior",
    sueldo: 58972,
    haceGuardia: true,
    lenguajes: ["PHP", "Java", "C#", "JavaScript", "Ruby"],
  },
  {
    nombre: "Josie Mullen",
    pais: "Brasil",
    edad: 26,
    area: "Seguridad",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 51718,
    haceGuardia: true,
    lenguajes: ["C#", "Java"],
  },
  {
    nombre: "Amelia Rhodes",
    pais: "México",
    edad: 42,
    area: "Soporte",
    puesto: "Architect",
    seniority: "Junior",
    sueldo: 76394,
    haceGuardia: true,
    lenguajes: ["PHP"],
  },
  {
    nombre: "George Richardson",
    pais: "Brasil",
    edad: 33,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Junior",
    sueldo: 63200,
    haceGuardia: true,
    lenguajes: ["JavaScript", "PHP", "Ruby"],
  },
  {
    nombre: "Lopez Simon",
    pais: "Uruguay",
    edad: 33,
    area: "Infraestructura",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 15556,
    haceGuardia: true,
    lenguajes: ["PHP", "JavaScript", "Java", "Python"],
  },
  {
    nombre: "Bentley Odonnell",
    pais: "Brasil",
    edad: 33,
    area: "Desarrollo",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 41923,
    haceGuardia: false,
    lenguajes: ["C#", "JavaScript", "Python", "Ruby"],
  },
  {
    nombre: "Witt Hansen",
    pais: "México",
    edad: 23,
    area: "Infraestructura",
    puesto: "Backend Developer",
    seniority: "Junior",
    sueldo: 34951,
    haceGuardia: true,
    lenguajes: ["JavaScript", "PHP", "Ruby", "Python"],
  },
  {
    nombre: "Isabelle Duran",
    pais: "Perú",
    edad: 30,
    area: "Desarrollo",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 41876,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Trina Beach",
    pais: "Venezuela",
    edad: 41,
    area: "Soporte",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 79688,
    haceGuardia: false,
    lenguajes: ["PHP", "JavaScript", "Python", "Java", "C#"],
  },
  {
    nombre: "Rose Valenzuela",
    pais: "Argentina",
    edad: 44,
    area: "Infraestructura",
    puesto: "Frontend Developer",
    seniority: "Trainee",
    sueldo: 35010,
    haceGuardia: false,
    lenguajes: ["JavaScript", "C#", "Python", "Ruby"],
  },
  {
    nombre: "Nadia Conrad",
    pais: "Colombia",
    edad: 20,
    area: "Desarrollo",
    puesto: "Backend Developer",
    seniority: "Senior",
    sueldo: 41377,
    haceGuardia: false,
    lenguajes: ["JavaScript", "Java", "Python", "PHP", "Ruby"],
  },
  {
    nombre: "Minnie Mcfadden",
    pais: "Uruguay",
    edad: 47,
    area: "Infraestructura",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 45466,
    haceGuardia: false,
    lenguajes: ["JavaScript", "C#", "PHP", "Ruby"],
  },
  {
    nombre: "Victoria Cleveland",
    pais: "Colombia",
    edad: 46,
    area: "Infraestructura",
    puesto: "DevOps",
    seniority: "Junior",
    sueldo: 39982,
    haceGuardia: true,
    lenguajes: ["C#", "Ruby", "Python", "PHP", "JavaScript"],
  },
  {
    nombre: "Kirkland Downs",
    pais: "Venezuela",
    edad: 20,
    area: "QA",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 53821,
    haceGuardia: false,
    lenguajes: ["Python"],
  },
  {
    nombre: "Mcclain Coffey",
    pais: "Colombia",
    edad: 30,
    area: "Desarrollo",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 24530,
    haceGuardia: false,
    lenguajes: ["PHP", "Java"],
  },
  {
    nombre: "Essie Fowler",
    pais: "Uruguay",
    edad: 42,
    area: "Seguridad",
    puesto: "Data analyst",
    seniority: "Senior",
    sueldo: 24168,
    haceGuardia: true,
    lenguajes: [],
  },
  {
    nombre: "Berta Burch",
    pais: "Chile",
    edad: 26,
    area: "Desarrollo",
    puesto: "Backend Developer",
    seniority: "Trainee",
    sueldo: 20568,
    haceGuardia: true,
    lenguajes: ["C#", "JavaScript", "Ruby", "PHP", "Java", "Python"],
  },
  {
    nombre: "Delacruz Dale",
    pais: "Perú",
    edad: 32,
    area: "Infraestructura",
    puesto: "Backend Developer",
    seniority: "Trainee",
    sueldo: 43729,
    haceGuardia: true,
    lenguajes: ["Ruby", "C#"],
  },
  {
    nombre: "Mari Webb",
    pais: "Colombia",
    edad: 37,
    area: "Soporte",
    puesto: "Tester",
    seniority: "Senior",
    sueldo: 82682,
    haceGuardia: true,
    lenguajes: ["Ruby", "C#", "JavaScript", "PHP", "Python"],
  },
  {
    nombre: "Mcconnell Maxwell",
    pais: "Perú",
    edad: 23,
    area: "Seguridad",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 55068,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Rich Wallace",
    pais: "Perú",
    edad: 35,
    area: "Soporte",
    puesto: "Data analyst",
    seniority: "Junior",
    sueldo: 49050,
    haceGuardia: false,
    lenguajes: ["Python", "PHP", "C#", "JavaScript", "Ruby"],
  },
  {
    nombre: "Dunlap Mullins",
    pais: "Argentina",
    edad: 45,
    area: "Soporte",
    puesto: "Analyst",
    seniority: "Senior",
    sueldo: 81267,
    haceGuardia: false,
    lenguajes: ["PHP", "C#", "JavaScript", "Java", "Python", "Ruby"],
  },
  {
    nombre: "Mercedes Roman",
    pais: "Argentina",
    edad: 48,
    area: "Infraestructura",
    puesto: "Frontend Developer",
    seniority: "Senior",
    sueldo: 97992,
    haceGuardia: true,
    lenguajes: ["Java", "PHP", "C#"],
  },
  {
    nombre: "Tabitha Charles",
    pais: "Chile",
    edad: 26,
    area: "Desarrollo",
    puesto: "Backend Developer",
    seniority: "Junior",
    sueldo: 71246,
    haceGuardia: false,
    lenguajes: ["JavaScript", "PHP", "Ruby"],
  },
  {
    nombre: "Kerry Carney",
    pais: "México",
    edad: 29,
    area: "Seguridad",
    puesto: "Data analyst",
    seniority: "Senior",
    sueldo: 21462,
    haceGuardia: true,
    lenguajes: ["JavaScript", "Java", "Python", "Ruby", "C#", "PHP"],
  },
  {
    nombre: "Knox Cash",
    pais: "Argentina",
    edad: 21,
    area: "QA",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 40408,
    haceGuardia: false,
    lenguajes: ["Java", "JavaScript", "PHP"],
  },
  {
    nombre: "Goodwin Griffith",
    pais: "México",
    edad: 34,
    area: "Soporte",
    puesto: "Frontend Developer",
    seniority: "Trainee",
    sueldo: 42841,
    haceGuardia: false,
    lenguajes: ["JavaScript", "C#"],
  },
  {
    nombre: "Shelly Bryant",
    pais: "Venezuela",
    edad: 40,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Senior",
    sueldo: 28972,
    haceGuardia: false,
    lenguajes: ["Java"],
  },
  {
    nombre: "Aimee Robertson",
    pais: "Venezuela",
    edad: 22,
    area: "Desarrollo",
    puesto: "Backend Developer",
    seniority: "Junior",
    sueldo: 35908,
    haceGuardia: true,
    lenguajes: ["C#"],
  },
  {
    nombre: "Wendi Case",
    pais: "Perú",
    edad: 25,
    area: "Infraestructura",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 58497,
    haceGuardia: false,
    lenguajes: ["PHP", "C#", "JavaScript", "Ruby", "Python"],
  },
  {
    nombre: "Rocha Jordan",
    pais: "Venezuela",
    edad: 29,
    area: "Soporte",
    puesto: "DevOps",
    seniority: "Semisenior",
    sueldo: 24891,
    haceGuardia: false,
    lenguajes: ["C#", "Ruby", "JavaScript"],
  },
  {
    nombre: "Tracy Hoover",
    pais: "Bolivia",
    edad: 30,
    area: "Soporte",
    puesto: "Backend Developer",
    seniority: "Senior",
    sueldo: 66318,
    haceGuardia: false,
    lenguajes: ["PHP", "Python", "Java", "Ruby"],
  },
  {
    nombre: "Schultz Mooney",
    pais: "México",
    edad: 27,
    area: "QA",
    puesto: "DevOps",
    seniority: "Junior",
    sueldo: 48811,
    haceGuardia: true,
    lenguajes: ["Ruby", "Java", "Python", "PHP"],
  },
  {
    nombre: "Emma Head",
    pais: "Venezuela",
    edad: 35,
    area: "Desarrollo",
    puesto: "Analyst",
    seniority: "Senior",
    sueldo: 33611,
    haceGuardia: false,
    lenguajes: ["PHP", "Ruby", "JavaScript", "Java"],
  },
  {
    nombre: "Norris Compton",
    pais: "Perú",
    edad: 40,
    area: "Soporte",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 66554,
    haceGuardia: false,
    lenguajes: ["Python", "C#", "JavaScript", "PHP"],
  },
  {
    nombre: "Francine Beasley",
    pais: "Brasil",
    edad: 29,
    area: "Infraestructura",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 24640,
    haceGuardia: true,
    lenguajes: ["Java", "Python", "PHP", "Ruby"],
  },
  {
    nombre: "Nieves Crane",
    pais: "Paraguay",
    edad: 27,
    area: "Soporte",
    puesto: "Architect",
    seniority: "Semisenior",
    sueldo: 58441,
    haceGuardia: false,
    lenguajes: ["JavaScript", "Ruby", "C#"],
  },
  {
    nombre: "Hurley House",
    pais: "Chile",
    edad: 30,
    area: "Soporte",
    puesto: "Data analyst",
    seniority: "Junior",
    sueldo: 69383,
    haceGuardia: false,
    lenguajes: ["Python", "PHP"],
  },
  {
    nombre: "Tanisha Hendrix",
    pais: "Chile",
    edad: 34,
    area: "Soporte",
    puesto: "Frontend Developer",
    seniority: "Senior",
    sueldo: 96636,
    haceGuardia: true,
    lenguajes: ["Java", "Ruby", "JavaScript"],
  },
  {
    nombre: "Tameka Holder",
    pais: "Brasil",
    edad: 31,
    area: "Seguridad",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 26627,
    haceGuardia: false,
    lenguajes: ["Python", "Ruby"],
  },
  {
    nombre: "Nichole Boone",
    pais: "Argentina",
    edad: 24,
    area: "Seguridad",
    puesto: "Frontend Developer",
    seniority: "Trainee",
    sueldo: 62911,
    haceGuardia: false,
    lenguajes: ["C#", "Java", "PHP"],
  },
  {
    nombre: "Latonya Lamb",
    pais: "Bolivia",
    edad: 36,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 74607,
    haceGuardia: true,
    lenguajes: ["Ruby"],
  },
  {
    nombre: "Espinoza Yang",
    pais: "Venezuela",
    edad: 43,
    area: "Seguridad",
    puesto: "DevOps",
    seniority: "Junior",
    sueldo: 80216,
    haceGuardia: false,
    lenguajes: ["C#", "PHP", "Ruby"],
  },
  {
    nombre: "Erma Jenkins",
    pais: "Perú",
    edad: 35,
    area: "Infraestructura",
    puesto: "Analyst",
    seniority: "Trainee",
    sueldo: 32293,
    haceGuardia: false,
    lenguajes: ["C#", "JavaScript", "Python", "PHP"],
  },
  {
    nombre: "Eugenia Carpenter",
    pais: "Chile",
    edad: 22,
    area: "Soporte",
    puesto: "DevOps",
    seniority: "Senior",
    sueldo: 93034,
    haceGuardia: false,
    lenguajes: ["Java", "JavaScript", "Ruby", "Python"],
  },
  {
    nombre: "Atkins English",
    pais: "Paraguay",
    edad: 28,
    area: "Seguridad",
    puesto: "Analyst",
    seniority: "Semisenior",
    sueldo: 84672,
    haceGuardia: true,
    lenguajes: ["PHP"],
  },
  {
    nombre: "Shelby Estes",
    pais: "Venezuela",
    edad: 38,
    area: "Seguridad",
    puesto: "Backend Developer",
    seniority: "Senior",
    sueldo: 44650,
    haceGuardia: true,
    lenguajes: ["Python", "Java", "C#", "PHP", "JavaScript"],
  },
  {
    nombre: "Kimberly Hood",
    pais: "Colombia",
    edad: 41,
    area: "Seguridad",
    puesto: "Analyst",
    seniority: "Senior",
    sueldo: 79572,
    haceGuardia: false,
    lenguajes: ["Ruby"],
  },
  {
    nombre: "Socorro Reid",
    pais: "Bolivia",
    edad: 45,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 51162,
    haceGuardia: false,
    lenguajes: ["JavaScript", "C#", "PHP"],
  },
  {
    nombre: "Marguerite Dawson",
    pais: "México",
    edad: 31,
    area: "Soporte",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 39509,
    haceGuardia: true,
    lenguajes: ["Ruby", "Java", "PHP"],
  },
  {
    nombre: "Marilyn William",
    pais: "Paraguay",
    edad: 20,
    area: "Seguridad",
    puesto: "DevOps",
    seniority: "Trainee",
    sueldo: 34648,
    haceGuardia: true,
    lenguajes: ["Python", "Ruby", "JavaScript", "Java"],
  },
  {
    nombre: "Betsy Bates",
    pais: "Paraguay",
    edad: 36,
    area: "Soporte",
    puesto: "Tester",
    seniority: "Trainee",
    sueldo: 55152,
    haceGuardia: true,
    lenguajes: ["Ruby", "PHP"],
  },
  {
    nombre: "Harrison Walters",
    pais: "Perú",
    edad: 42,
    area: "Infraestructura",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 44306,
    haceGuardia: true,
    lenguajes: ["C#", "Ruby", "Python", "Java", "JavaScript"],
  },
  {
    nombre: "Conley Mcgee",
    pais: "Colombia",
    edad: 22,
    area: "Infraestructura",
    puesto: "Data analyst",
    seniority: "Junior",
    sueldo: 83793,
    haceGuardia: false,
    lenguajes: ["PHP", "Ruby", "JavaScript", "Java"],
  },
  {
    nombre: "Angelica Adkins",
    pais: "Perú",
    edad: 45,
    area: "Seguridad",
    puesto: "Tester",
    seniority: "Junior",
    sueldo: 35471,
    haceGuardia: false,
    lenguajes: ["Ruby"],
  },
  {
    nombre: "Maynard Greer",
    pais: "Brasil",
    edad: 43,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Junior",
    sueldo: 21202,
    haceGuardia: false,
    lenguajes: ["JavaScript", "PHP"],
  },
  {
    nombre: "Marjorie Griffin",
    pais: "Colombia",
    edad: 28,
    area: "Seguridad",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 64591,
    haceGuardia: false,
    lenguajes: ["JavaScript", "Python"],
  },
  {
    nombre: "Marcia Allen",
    pais: "México",
    edad: 33,
    area: "Infraestructura",
    puesto: "DevOps",
    seniority: "Trainee",
    sueldo: 71814,
    haceGuardia: false,
    lenguajes: ["PHP", "Ruby", "JavaScript", "Java", "C#"],
  },
  {
    nombre: "Mclaughlin Rocha",
    pais: "Perú",
    edad: 21,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Senior",
    sueldo: 68572,
    haceGuardia: true,
    lenguajes: ["Java", "JavaScript", "Ruby", "C#"],
  },
  {
    nombre: "Spence Ingram",
    pais: "Bolivia",
    edad: 40,
    area: "Desarrollo",
    puesto: "Tester",
    seniority: "Senior",
    sueldo: 34398,
    haceGuardia: true,
    lenguajes: ["Ruby", "C#", "PHP", "JavaScript"],
  },
  {
    nombre: "Kendra Bray",
    pais: "Bolivia",
    edad: 31,
    area: "QA",
    puesto: "Analyst",
    seniority: "Trainee",
    sueldo: 82612,
    haceGuardia: true,
    lenguajes: ["Ruby", "C#", "PHP", "Python", "Java"],
  },
  {
    nombre: "Burton Parsons",
    pais: "Argentina",
    edad: 42,
    area: "Soporte",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 94155,
    haceGuardia: false,
    lenguajes: ["Ruby"],
  },
  {
    nombre: "Dollie Wilkins",
    pais: "Colombia",
    edad: 32,
    area: "Seguridad",
    puesto: "Data analyst",
    seniority: "Semisenior",
    sueldo: 25161,
    haceGuardia: true,
    lenguajes: ["JavaScript", "C#", "Python", "Ruby", "Java", "PHP"],
  },
  {
    nombre: "Shauna Coleman",
    pais: "Bolivia",
    edad: 20,
    area: "Seguridad",
    puesto: "Frontend Developer",
    seniority: "Junior",
    sueldo: 29595,
    haceGuardia: false,
    lenguajes: ["JavaScript", "PHP", "C#", "Ruby"],
  },
  {
    nombre: "Cross Weber",
    pais: "Paraguay",
    edad: 40,
    area: "Soporte",
    puesto: "Backend Developer",
    seniority: "Semisenior",
    sueldo: 55857,
    haceGuardia: true,
    lenguajes: ["Ruby"],
  },
  {
    nombre: "Mueller Whitehead",
    pais: "Perú",
    edad: 21,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Semisenior",
    sueldo: 60691,
    haceGuardia: true,
    lenguajes: ["Ruby", "Java", "JavaScript", "C#"],
  },
  {
    nombre: "Joann Tillman",
    pais: "Colombia",
    edad: 43,
    area: "Infraestructura",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 37502,
    haceGuardia: true,
    lenguajes: ["JavaScript", "Python", "Java", "C#", "Ruby", "PHP"],
  },
  {
    nombre: "Rosalind French",
    pais: "Colombia",
    edad: 22,
    area: "QA",
    puesto: "Backend Developer",
    seniority: "Junior",
    sueldo: 58103,
    haceGuardia: false,
    lenguajes: [],
  },
  {
    nombre: "Kaufman Vasquez",
    pais: "Argentina",
    edad: 37,
    area: "Seguridad",
    puesto: "Data analyst",
    seniority: "Junior",
    sueldo: 97466,
    haceGuardia: false,
    lenguajes: ["Ruby", "C#", "PHP", "JavaScript", "Python"],
  },
  {
    nombre: "Inez Emerson",
    pais: "Perú",
    edad: 38,
    area: "Infraestructura",
    puesto: "Frontend Developer",
    seniority: "Senior",
    sueldo: 30992,
    haceGuardia: true,
    lenguajes: ["C#", "Java", "Python", "PHP"],
  },
  {
    nombre: "Acevedo Henderson",
    pais: "Brasil",
    edad: 20,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 55891,
    haceGuardia: true,
    lenguajes: ["PHP", "Java", "JavaScript"],
  },
  {
    nombre: "Erin Guerrero",
    pais: "Bolivia",
    edad: 33,
    area: "Seguridad",
    puesto: "Architect",
    seniority: "Semisenior",
    sueldo: 22605,
    haceGuardia: false,
    lenguajes: ["JavaScript", "Ruby", "C#"],
  },
  {
    nombre: "Camacho Serrano",
    pais: "Brasil",
    edad: 45,
    area: "Soporte",
    puesto: "Analyst",
    seniority: "Semisenior",
    sueldo: 49426,
    haceGuardia: true,
    lenguajes: ["PHP", "Ruby", "Java"],
  },
  {
    nombre: "Mcleod Romero",
    pais: "México",
    edad: 32,
    area: "Infraestructura",
    puesto: "DevOps",
    seniority: "Trainee",
    sueldo: 33800,
    haceGuardia: false,
    lenguajes: ["PHP"],
  },
  {
    nombre: "Francesca Bird",
    pais: "Paraguay",
    edad: 22,
    area: "Seguridad",
    puesto: "Backend Developer",
    seniority: "Trainee",
    sueldo: 42628,
    haceGuardia: false,
    lenguajes: ["Python", "Java"],
  },
  {
    nombre: "Avila Roy",
    pais: "Perú",
    edad: 32,
    area: "Soporte",
    puesto: "Analyst",
    seniority: "Semisenior",
    sueldo: 84245,
    haceGuardia: false,
    lenguajes: ["Ruby", "C#", "Java", "PHP"],
  },
  {
    nombre: "Delia Ellison",
    pais: "Argentina",
    edad: 44,
    area: "Infraestructura",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 86942,
    haceGuardia: false,
    lenguajes: ["C#", "JavaScript"],
  },
  {
    nombre: "Lakeisha Martin",
    pais: "Venezuela",
    edad: 44,
    area: "Desarrollo",
    puesto: "Architect",
    seniority: "Trainee",
    sueldo: 24946,
    haceGuardia: false,
    lenguajes: ["Ruby", "JavaScript", "C#"],
  },
  {
    nombre: "Cummings Woods",
    pais: "Venezuela",
    edad: 31,
    area: "QA",
    puesto: "Backend Developer",
    seniority: "Senior",
    sueldo: 74987,
    haceGuardia: true,
    lenguajes: ["Ruby", "JavaScript", "PHP", "Python", "Java"],
  },
];
